version: "3"

services:
  app:
    build: .
    # entrypoint: ./entrypoint.sh
    command: ["./entrypoint.sh"]
    container_name: apivendas-api
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/mysql
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - "5432:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=hack09exe
      - MYSQL_DATABASE=apivendas
      - MYSQL_ROOT_PASSWORD=hack09exe

  redis:
    image: "bitnami/redis:latest"
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
